### PR TITLE
Include the creation date and time in the footer

### PR DESCRIPTION
**Pull request by p-vitt**
We wanted to have the creation date somewhere in the documentation. This is nice to see whether the documentation was created during the nightly build as well as having the ability to determine the age of a particular documentation.

To activate it, one has to specify `print_creation_date = True` in the project file. By default, the ISO format is used to print the date.

### CODE REVIEW

**Comment by szaghi** [comment]
:+1:

**Comment by cmacmackin** [comment]
This looks good. My only thought is that it might be nice to give people the option to specify a [date format string](https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior). Specifying `print_creation_date = True` would still give you the ISO default, but people could also set it to a format string. Thoughts?

**Comment by p-vitt** [comment]
I also thought about that but wasn't able to come up with a proper solution. I'm not yet familiar with Ford and don't know the code very well, so I tried to prevent any side effect by starting rather simple.

**Comment by cmacmackin** [comment]
Don't worry. I'll add the code in to do that before I merge the pull 
request.

On 22/03/16 14:27, pvitt wrote:
>
> I also thought about that but wasn't able to come up with a proper 
> solution. I'm not yet familiar with Ford and don't know the code very 
> well, so I tried to prevent any side effect by starting rather simple.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/pull/115#issuecomment-199838673>
>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>

**Comment by p-vitt** [comment]
A very convenient solution would be to not call `datetime.now().isoformat()`, but call `datetime.now().strftime()` and store the format string in `creation_date`. This is also a quite transparent solution, as `strftime` supports platform-specific formattings. Thus Ford doesn't need to care about whether a particular format is present on a given platform, because it's up to the user to select the favorite one (which hopefully is present at the user's machine).

The downside is that the default can't be `datetime.now().isoformat()` anymore, which I find quite handy. On the other hand, a default format string `'%Y-%m-%dT%H:%M:%S.%f%z'` can replace it.

I will push another changeset to this pull request contain these changes.

**Comment by p-vitt** [comment]
Are you planning to merge the pull request? Otherwise we have to patch FORD locally. I don't want to put any pressure, I just recognized that there was a new release and the PR is still pending.

**Comment by cmacmackin** [comment]
I will pull it in. The reason I didn't include it in the last release is 
because that was a bug-fix release only. I generally don't like putting 
out releases with only one new feature.

On 04/04/16 17:07, pvitt wrote:
>
> Are you planning to merge the pull request? Otherwise we have to patch 
> FORD locally. I don't want to put any pressure, I just recognized that 
> there was a new release and the PR is still pending.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/pull/115#issuecomment-205369590>
>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>

**Comment by p-vitt** [comment]
Thanks for the fast reply. I already assumed that, just wanted to be sure.

**Pull request merged**
