### PR TITLE
Introduced a maximal graph depth option to limit graph sizes.

### PR DESCRIPTION
**Pull request by haraldkl**
In #176 the need to limit overly large graphs is raised.
This patch tries to offer a kind of solution by allowing the user to restrict the maximal graph depth (in hops from the root node).

This setting can be configured in the project meta data by defining `graph_maxdata:`
The default is 10000 to basically allow recursion without limits.
Individual objects may overwrite this for graphs, where they are
the root node.

For us, this is a useful feature, as we otherwise suffer from really long rendering times of the resulting graphs, where you anyway get lost.

### CODE REVIEW

**Comment by cmacmackin** [comment]
Thanks, this looks like a great feature. I'll include it in the next release, when I finally have time to work on FORD again.

**Comment by zbeekman** [comment]
These look like great changes. I may have to use your fork until Chris gets around to merging this.

**Comment by haraldkl** [comment]
Sure. I now notice, that the pull request is updated with all the commits that I pulled in from other repositories as well. Obviously, I am not that used to git and github. Should I create a separate feature branch for this graph limitation stuff and create a new pull request for that?

**Comment by cmacmackin** [comment]
No, it's fine as is, I think.

**Comment by cmacmackin** [comment]
There seems to be a lot of combined work between this pull request and that in #178. @haraldkl, would it be possible for you to completely pull in the remaining changes in #178 to this branch? As it stands now I'm a bit confused as to how the two branches relate to each other, and just combining them into a single pull request seems the simplest solution.

**Comment by haraldkl** [comment]
Yes, of course. I am sorry about the commits all ending up in the same pull request.

**Comment by haraldkl** [comment]
Actually, I think, that everything that was requested by #178, has been merged into here by https://github.com/haraldkl/ford/commit/7d2f02de867415b77bab34141d79b0dc3404910c. Thus, it should already be fine to stick with this pull request only. Do you want me to try to resolve the conflicts?

**Comment by cmacmackin** [comment]
No, I don't think all of them are pulled in. For example, I don't see 441a406 (the latest commit on #178) in your branch. Don't worry about the conflicts--I'll sort those out myself. I make it part of the process where I check everything over.

**Comment by cmacmackin** [comment]
> I fear, that specific commit is duplicated and you already merged it in 9d00679.
Um, [no I didn't](https://github.com/cmacmackin/ford/pull/201/commits).
>It would be great, if you could also include the external stuff, but I would create a separate pull request for that, with the hope that it creates less confusion.
After I have merged in this PR, could you please rebase to the FORD master branch and create this new pull request.

**Comment by haraldkl** [comment]
> Um, no I didn't.
What I meant is, that 441a406ad792152192acf69390129faf4d6a59b4 is a duplicate of 53364d209209608920f4c666da0e62c9dd0c8070.

> could you please rebase to the FORD master branch and create this new pull request.
Yes, I'll do that.

**Comment by cmacmackin** [comment]
>What I meant is, that 441a406 is a duplicate of 53364d2.

Ah, my apologies.

>Yes, I'll do that.

Great, thanks :)

**Comment by Schildkroete23** [comment]
I am sorry for the confusion.

#178 was just intended to fix the hidden anchors (first two commits which are already part of this PR) and I was not aware of the fact that everything which I commit later to this branch is added automatically to the PR. I think the only commit which may be added here is 83a94f5 as it fixes the links to intrinsic modules caused by ab84c5d.

**Comment by cmacmackin** [comment]
Okay, finally took another look at this. I checked over all of your code. I can't say I understood everything you did with the graphs module, but nor have I really tried to wrap my head around it. The most important thing was that I confirmed you didn't put in anything to steel data off of someone's computer! I merged it in and (I think) resolved all of the conflicts. When I tried actually running it, though, I got
```
Generating graphs...
Traceback (most recent call last):
  File "/home/chris/Code/ford/venv/bin/ford", line 11, in <module>
    load_entry_point('FORD', 'console_scripts', 'ford')()
  File "/home/chris/Code/ford/ford/__init__.py", line 373, in run
    main(proj_data,proj_docs,md)
  File "/home/chris/Code/ford/ford/__init__.py", line 360, in main
    docs = ford.output.Documentation(proj_data,proj_docs_,project,page_tree)
  File "/home/chris/Code/ford/ford/output.py", line 93, in __init__
    self.graphs.graph_all()
  File "/home/chris/Code/ford/ford/graphmanager.py", line 87, in graph_all
    obj.inhergraph = ford.graphs.InheritsGraph(obj,self.webdir)
  File "/home/chris/Code/ford/ford/graphs.py", line 465, in __init__
    self.add_nodes(self.root)
  File "/home/chris/Code/ford/ford/graphs.py", line 828, in add_nodes
    if not self.addToGraph(hopNodes, hopEdges, nesting):
  File "/home/chris/Code/ford/ford/graphs.py", line 498, in addToGraph
    color=e[3])
IndexError: tuple index out of range
```
Any idea what's causing this? If not I can take a closer look myself tomorrow. It's late for me here and I just thought I'd put this out there now.

**Comment by Schildkroete23** [comment]
I forgot to set the line style in the InheritsGraph class. Sorry for that. This is fixed now with 668fb7bd363679bd8b7c2d16af4f9736d6c1cc30. I think this fixes your issue.

**Comment by cmacmackin** [comment]
As you can see I've merged in your changes. However, there are a few issues I want to resolve, such as the overview plot of the type-structure not being produced for me. I'm not sure I fully understand your code. In particular, what exactly are the hop-lists and how do they work? What are you trying to do in the `__str__` methods of the graphs in your logic about whether to produce one and whether to do so in a table or not. I can't seem to make it produce table output, even when playing with the maxdepth and mindepth settings.

**Comment by haraldkl** [comment]
Hey, thanks for looking into this. I am not quite sure, about the type-structure. To me, it looks like intrinsic types are not included in the graph, but derived types are. In our documentation, there is, for example, a type-structure graph in https://geb.sts.nt.uni-siegen.de/doxy/treelm/type/tem_communication_type.html, but the components of intrinsic type are missing. Thus, in https://geb.sts.nt.uni-siegen.de/doxy/treelm/type/grw_intarray_type.html, where the type has only components of intrinsic type there is no graph at all.

An illustration of the table being produced can be found in https://geb.sts.nt.uni-siegen.de/doxy/treelm/module/env_module.html, here the used-by list is almost all other modules of the project, so this is rendered as a table.
The hop-lists store the nodes which exceed the total node count, this is needed if we render them later on in a table, otherwise, those nodes get discarded. The depth of the graph (maximal number of hops) is one criterion we want to limit the depth of the graph with. Another is the total number of nodes in the graph. We try to limit the depth of the graph to never have more than the configured maximum number of nodes, and finally, if the first level of the graph already has too many nodes we rather want to show it as a table as the graph would anyway mostly resemble a simple list.

**Comment by Schildkroete23** [comment]
Are the intrinsic types supposed to be shown in the type graphs?

**Comment by cmacmackin** [comment]
@Schildkroete23 No. Are they showing up for you?

**Comment by Schildkroete23** [comment]
No. I am just wondering why the type graphs are not being produced for you. As Harald showed, for us the generation of the type graphs seems to work. Or what do you mean by overview plot of the type-structure?

**Comment by haraldkl** [comment]
I now tried  6256fef on our Aotus code, with a configuration of

    graph: true
    graph_maxdepth: 2
    graph_maxnodes: 4

and what I not there now is, that the graph, which is shown on the [derived types page](https://geb.sts.nt.uni-siegen.de/doxy/aotus/lists/types.html) is not present anymore. Is this the overview plot you meant? This is also true for the graph on the [modules page](https://geb.sts.nt.uni-siegen.de/doxy/aotus/lists/modules.html). When the graphs are generated without the `graph_maxdepth` and `graph_maxnodes` settings they are shown like in the links to the Aotus documentation.

Are these the graphs that are missing, or are there other graphs you saw missing?

I believe the graph limiting approach does not properly deal with graphs when there are multiple independent root nodes.

**Comment by cmacmackin** [comment]
@haraldkl yes, that's what I meant by the overview plots. Funnily enough, I do see the module graph in my test, but not the type graph or the file graph. I think you're correct that it is not properly handling multiple independent nodes. I _think_ the problem is with this part of the `__str__` method (ford/graphs.py:502-509):
```python
    def __str__(self):
        # do not generate overview graphs if maximum number of nodes gets
        # exceeded
        if ((len(self.added) <= len(self.root)
                and isinstance(self, (ModuleGraph, FileGraph, TypeGraph,
                                      CallGraph)))
                or (len(self.added) + len(self.hopNodes) <= len(self.root))):
            return ''
```
The overview graphs receive all nodes as root nodes, meaning that `len(self.added) == len(self.root)` and this test would interpret that to mean the maximum number of nodes was exceeded.

**Comment by haraldkl** [comment]
I think this works mostly as designed. The logic in __str__ ensures that we only draw the plot if at least all the roots were added to the graph, as we otherwise would show an incomplete and therefore misleading graph. We can not really make use of the table approach for multiple roots, so this is excluded for these graphs, but otherwise, we might have the option to render the first level of the graph as a table which is realized with the hopNodes list here.

Now the overview graphs might get pretty fast pretty large. And if they have too many nodes the browsers started to choke on displaying them. They are also not too useful when they are too large so that we would rather not show them at all if they are too big. And this is configured with the `graph_maxnodes` setting. Graphs that would contain more than `graph_maxnodes` nodes are not rendered, but those with fewer nodes are.

If you set the `graph_maxnodes` to a sufficiently large number, do you get the type graph? Has the module graph by any chance fewer nodes than your configured `graph_maxnodes`?
I also never get a graph in the files overview, even when taking out the `graph_*` options completely.

The idea of the various settings introduced by this change are:

- `graph_maxdepth`: only follow links from node to node to the given depth
- `graph_maxnodes`: do not attempt to render graphs that would contain more than this many nodes
- `graph_mindepth`: follow at least that many links from root nodes, even if this results in more nodes than configured in `graph_maxnodes`

**Comment by haraldkl** [comment]
I think 12f558d2814d30487fee1a559392d5bd3a86fe20 fixes the issue with the overview graphs, and clarifies the logic about when to include the graph and when not to include it. This now produces FileGraphs for me. Another quirk I found is that for the overview graphs there is max_nesting passed in, instead of nesting. I don't think it matters for them, but it might be a little bit confusing.

It might also be nice to return a div with a message about the graph not being rendered due to its size instead of an empty string.

**Comment by haraldkl** [comment]
I've added some commentary in 30098fe38447061d1024b3586be6d82c3c16b067 and changed the above mentioned nesting parameter in ce1428c0ba57989d9b3029d39f242c0cce6c078c. One problem with the logic as it is now, is that I ignore the min_nesting setting.
I think, the best solution for this would be to change the self.max_nodes setting if more nodes where added due to the min_nesting. I'll put that in another commit.

The question is then only, whether we should render some informing message when the graph is not created or truncated to point this out in the resulting HTML?
If so, I can also add that and then make a pull request out of those patches.

**Comment by haraldkl** [comment]
So the min_nesting concept does not really work with the overview graphs, as they anyway only do one hop that was the reason for the max_nesting passing that was reverted in ce1428c. I think it would be better to make it more explicit and create __init__ routines for those graphs where the min_nesting is set to 0 for these kinds of graph.

However, the logic for this gets quite convoluted for the user to understand what this is supposed to do. I am also not sure how useful such a setting actually is and am thinking that it may be better to remove this setting altogether.

**Comment by haraldkl** [comment]
I believe 99a5574f52ed27b171e2093b7b57fd5c467d724b now properly handles also graph_mindepth settings: The setting is ignored for graphs with multiple nodes, and otherwise we increase the number of allowed nodes for this graph dynamically if the mindepth requires us to include more nodes than given by the graph_maxnodes setting.

This mindepth option may be quite confusing and I am not sure whether it is worth having it. Let me know, wether it should rather be removed, and if we should do some box explaining missing graphs instead of empty strings. Should I create pull request from that branch (https://github.com/haraldkl/ford/tree/fix_graphlimiting)?

**Comment by cmacmackin** [comment]
Yes, I think mindepth should be removed. Don't put in a box explaining missing graphs; that doesn't look good on public docs. Perhaps just output a note to the command-line when the [--warn flag](https://github.com/cmacmackin/ford/wiki/Command-Line-Options#-w--warn)/option is specified. A new pull request would be great. If you can, please merge in the latest commits on master first.

**Comment by haraldkl** [comment]
OK, I'll remove the mindepth option, merge in the master branch and do a pull request from that.

**Comment by haraldkl** [comment]
Opened a pull request with these changes in #216.

**Pull request merged**
